---
- name: Ensure Python3 and related packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-dev
      - python3-proxmoxer
      - python3-requests
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Check Python3 version
  command: python3 --version
  register: python_version
  changed_when: false
  
- name: Display Python version
  debug:
    msg: "{{ python_version.stdout }}"
    verbosity: 1
