# yamllint disable
#cloud-config
network:
  version: 1
  config:
    - type: physical
      name: eth0
      subnets:
        - type: "{% if vm_ip_type == 'dhcp' %}dhcp{% else %}static{% endif %}"
{% if vm_ip_type != 'dhcp' %}
          address: "{{ vm_ip_address }}/{{ vm_ip_netmask }}"
          gateway: "{{ vm_ip_gateway }}"
{% if vm_ip_dns1 is defined %}
          dns_nameservers:
            - "{{ vm_ip_dns1 }}"
{% if vm_ip_dns2 is defined %}
            - "{{ vm_ip_dns2 }}"
{% endif %}
{% endif %}
{% endif %}

{% if vm_ip_dns1 is defined or vm_ip_dns2 is defined %}
    - type: nameserver
      address:
{% if vm_ip_dns1 is defined %}
        - "{{ vm_ip_dns1 }}"
{% endif %}
{% if vm_ip_dns2 is defined %}
        - "{{ vm_ip_dns2 }}"
{% endif %}
{% else %}
    - type: nameserver
      address:
        - 1.1.1.1
        - 8.8.8.8
{% endif %}
      search:
        - local