#cloud-config
hostname: {{ vm_name }}
manage_etc_hosts: true

# Set timezone
timezone: {{ linux_timezone }}

# Configure users
users:
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    # Password is dynamically generated
    passwd: "{{ ansible_password_hash | default('$6$rounds=4096$saltsalt$NZkG4VjEQJ9ZxXXfUJXbk5.Ql9QXCCgZYSH8z3NQzTH9kvI9kf/zShFEgXgxM.FzQRSyNn5oY5HJWBgMJXgBf/') }}"

# Configure password authentication
chpasswd:
  expire: false
  list: |
    ansible:ansible

# Install packages
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - sudo

# Run commands on first boot
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "Cloud-init setup completed" > /var/log/cloud-init-completed.log

# Configure SSH
ssh_pwauth: true
disable_root: false
