---
- name: Retrieve Proxmox VM information
  hosts: all
  become: true
  become_method: sudo
  roles:
    - proxmox-prerequisites
  tasks:
    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: '{{ proxmox_host }}'
        api_user: '{{ proxmox_user }}'
        api_password: '{{ proxmox_password }}'
        node: '{{ proxmox_node }}'
      register: proxmox_vms
      no_log: true
    
    - name: Create simplified VM list with specific details
      set_fact:
        vm_details: "{{ vm_details | default([]) + [{'name': item.name, 'status': item.status, 'vmid': item.vmid, 'cpu': item.cpus, 'memory': item.maxmem | human_readable, 'ip_addresses': item.net | default([]) | map(attribute='ip') | select('defined') | list}] }}"
      loop: "{{ proxmox_vms.proxmox_vms }}"
      when: proxmox_vms.proxmox_vms is defined
    
    - name: Display table header
      debug:
        msg: |
          +{{ '-' * 25 }}+{{ '-' * 10 }}+{{ '-' * 10 }}+{{ '-' * 8 }}+{{ '-' * 12 }}+{{ '-' * 25 }}+
          | {{ 'VM NAME' | ljust(23) }} | {{ 'VM ID' | ljust(8) }} | {{ 'STATUS' | ljust(8) }} | {{ 'CPU' | ljust(6) }} | {{ 'MEMORY' | ljust(10) }} | {{ 'IP ADDRESSES' | ljust(23) }} |
          +{{ '-' * 25 }}+{{ '-' * 10 }}+{{ '-' * 10 }}+{{ '-' * 8 }}+{{ '-' * 12 }}+{{ '-' * 25 }}+
        verbosity: 0

    - name: Display VM rows
      debug:
        msg: |
          | {{ item.name | truncate(23) | ljust(23) }} | {{ item.vmid | string | ljust(8) }} | {{ item.status | ljust(8) }} | {{ item.cpu | string | ljust(6) }} | {{ item.memory | string | ljust(10) }} | {{ (item.ip_addresses | default(['No IP']) | join(', ')) | truncate(23) | ljust(23) }} |
        verbosity: 0
      loop: "{{ vm_details | default([]) }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display table footer
      debug:
        msg: |
          +{{ '-' * 25 }}+{{ '-' * 10 }}+{{ '-' * 10 }}+{{ '-' * 8 }}+{{ '-' * 12 }}+{{ '-' * 25 }}+
          Total VMs: {{ vm_details | default([]) | length }}
        verbosity: 0
