---
- name: Create VM in Proxmox
  hosts: all
  become: true
  become_method: sudo
  roles:
    - proxmox-prerequisites
  
  vars:
    proxmox_api_host: "{{ proxmox_host }}"
    proxmox_api_user: "{{ proxmox_user }}"
    proxmox_api_password: "{{ proxmox_password }}"
    proxmox_node: "{{ proxmox_node }}"

  tasks:
    - name: Verify Proxmox API connection
      uri:
        # Extract just the hostname/IP from proxmox_host, then add the port explicitly
        url: "https://{{ proxmox_host.split(':')[0] }}:8006/api2/json/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ proxmox_api_user }}"
          password: "{{ proxmox_api_password }}"
        validate_certs: false
      register: proxmox_auth
      failed_when: proxmox_auth.status != 200
      
    - name: Display success message if connection is established
      debug:
        msg: "Successfully connected to Proxmox API"
      when: proxmox_auth.status == 200    # You can add your VM creation tasks here