---
- name: Retrieve Proxmox VM information
  hosts: all
  become: true
  become_method: sudo
  roles:
    - proxmox-prerequisites
  tasks:
    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: '{{ proxmox_host }}'
        api_user: '{{ proxmox_user }}'
        api_password: '{{ proxmox_password }}'
        node: '{{ proxmox_node }}'
      register: proxmox_vms
      no_log: true
    
    - name: Create simplified VM list with specific details
      set_fact:
        vm_details: "{{ vm_details | default([]) + [{'name': item.name, 'status': item.status, 'vmid': item.vmid, 'cpu': item.cpus, 'memory': item.maxmem | human_readable, 'ip_addresses': item.net | default([]) | map(attribute='ip') | select('defined') | list}] }}"
      loop: "{{ proxmox_vms.proxmox_vms | default([]) }}"
      when: "proxmox_vms.proxmox_vms is defined"
    
    - name: Display table header
      debug:
        msg: |
          +-------------------------+----------+----------+--------+------------+-------------------------+
          | VM NAME                 | VM ID    | STATUS   | CPU    | MEMORY     | IP ADDRESSES           |
          +-------------------------+----------+----------+--------+------------+-------------------------+
        verbosity: 0
      when: "vm_details is defined"

    - name: Display VM rows
      debug:
        msg: "| {{ '%-23s' | format(item.name | truncate(23)) }} | {{ '%-8s' | format(item.vmid) }} | {{ '%-8s' | format(item.status) }} | {{ '%-6s' | format(item.cpu) }} | {{ '%-10s' | format(item.memory) }} | {{ '%-23s' | format((item.ip_addresses | default(['No IP']) | join(', ')) | truncate(23)) }} |"
        verbosity: 0
      loop: "{{ vm_details | default([]) }}"
      loop_control:
        label: "{{ item.name }}"
      when: "vm_details is defined"

    - name: Display table footer
      debug:
        msg: |
          +-------------------------+----------+----------+--------+------------+-------------------------+
          Total VMs: {{ vm_details | default([]) | length }}
        verbosity: 0
      when: "vm_details is defined"