---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Install proxmoxer Python module
    pip:
      name: proxmoxer
      state: present

  - name: List all existing virtual machines on node
    community.general.proxmox_vm_info:
      api_host: '{{ proxmox_host }}'
      api_user: '{{ proxmox_user }}'
      api_password: '{{ proxmox_password }}'
      node: '{{ proxmox_node }}'
