---
- name: Retrieve Proxmox VM information
  hosts: all
  become: true
  become_method: sudo
  roles:
    - proxmox-prerequisites
  tasks:
    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: '{{ proxmox_host }}'
        api_user: '{{ proxmox_user }}'
        api_password: '{{ proxmox_password }}'
        node: '{{ proxmox_node }}'
      register: proxmox_vms
      no_log: true
    
    - name: Create simplified VM list with specific details
      set_fact:
        vm_details: "{{ vm_details | default([]) + [{'name': item.name, 'status': item.status, 'vmid': item.vmid, 'cpu': item.cpus, 'memory': item.maxmem | human_readable, 'ip_addresses': item.net | default([]) | map(attribute='ip') | select('defined') | list}] }}"
      loop: "{{ proxmox_vms.proxmox_vms }}"
      when: proxmox_vms.proxmox_vms is defined
    
    - name: Display VM details
      debug:
        msg: |
          VM Name: {{ item.name }}
          VM ID: {{ item.vmid }}
          Status: {{ item.status }}
          CPU: {{ item.cpu }}
          Memory: {{ item.memory }}
          IP Addresses: {{ item.ip_addresses | default(['No IP']) | join(', ') }}
        verbosity: 0
      loop: "{{ vm_details | default([]) }}"
