---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install python3-proxmoxer package
    apt:
      name: python3-proxmoxer
      state: present
      update_cache: yes

  - name: List all existing virtual machines on node
    community.general.proxmox_vm_info:
      api_host: '{{ proxmox_host }}'
      api_user: '{{ proxmox_user }}'
      api_password: '{{ proxmox_password }}'
      node: '{{ proxmox_node }}'
    register: proxmox_vms
  
  - name: Display VMs
    debug:
      var: proxmox_vms