---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Update and upgrade apt packages
    apt:
      update_cache: yes
      upgrade: yes
      force_apt_get: yes
      cache_valid_time: 3600
