---
- name: Upload Cloud-init templates to Proxmox
  hosts: proxmox
  become: true
  tasks:
    - name: Create snippets directory if it doesn't exist
      file:
        path: /var/lib/vz/snippets
        state: directory
        mode: '0755'

    - name: Upload cloud-init user template
      template:
        src: templates/cloud-init-user.yml
        dest: /var/lib/vz/snippets/cloud-init-user.yml
        mode: '0644'

    - name: Upload cloud-init network template
      template:
        src: templates/cloud-init-network.yml
        dest: /var/lib/vz/snippets/cloud-init-network.yml
        mode: '0644'
